MODEL:
  DETECTOR:
    TYPE: "DETRBasedSGGTR"

  DETECTION_HEADER:
    BOX_FORMAT: "bcxbcywh"

SOLVER:
  IMS_PER_BATCH: 4
  LOG_PERIOD: 10
  VISUALIZE_PERIOD: 1000
  VAL_PERIOD: 100000000000
  CHECKPOINT_PERIOD: 10
  MAX_EPOCHS: 500
  LR_DROP: 400

OUTPUT_DIR: "/p300/projects/scene_graph/sggtr/outputs/full_vg_detr_based_sggtr"
