MODEL:
  PRETRAINED: ''
  DETECTOR:
    TYPE: "SGGTR"
    ENC_LAYERS: 5
    DEC_LAYERS: 5
    NUM_OBJ_QUERY: 20
    NUM_HIDDEN_REL_QUERY: 20

  DETECTION_HEADER:
    BOX_FORMAT: "bcxbcywh"
    # NUM_OBJ_CLASS: 100 # 150
    # NUM_REL_CLASS: 70 # 50
    # NUM_OBJ_CLASS: 150
    # NUM_REL_CLASS: 50
    NUM_OBJ_CLASS: 90
    NUM_REL_CLASS: 118

LOSS:
  OD_ONLY: False
  SGG_ONLY: False
  REL_CLS_COEF: 100

  NO_REL_CLS_WEIGHT: 0.05

DATASETS:
  TRAIN: ("HICO_train", ) # ("VG_stanford_filtered_with_attribute_train", )
  VAL: ("HICO_val", ) # ("VG_stanford_filtered_with_attribute_val", )
  TEST: ("HICO_test", ) # ("VG_stanford_filtered_with_attribute_test", )

# DATASETS:
#   TRAIN: ("VRD_train", ) # ("VG_stanford_filtered_with_attribute_train", )
#   VAL: ("VRD_val", ) # ("VG_stanford_filtered_with_attribute_val", )
#   TEST: ("VRD_test", ) # ("VG_stanford_filtered_with_attribute_test", )

# DATASETS:
#   TRAIN: ("VG_stanford_filtered_with_attribute_train", )
#   VAL: ("VG_stanford_filtered_with_attribute_test", )
#   TEST: ("VG_stanford_filtered_with_attribute_test", )

SOLVER:
  IMS_PER_BATCH: 3
  LOG_PERIOD: 10
  VISUALIZE_PERIOD: 1000000000
  VAL_PERIOD: 100000000
  CHECKPOINT_PERIOD: 2
  MAX_EPOCHS: 90
  LR_DROP: 80
  LR: 1e-4

TEST:
  IMS_PER_BATCH: 4

OUTPUT_DIR: "/p300/projects/scene_graph/sggtr/outputs/full_hico_sggtr_e5d5_ob_sgg_bbwh_3"
