MODEL:
  DETECTOR:
    TYPE: "SGGTR"

  DETECTION_HEADER:
    BOX_FORMAT: "bcxbcywh"

SOLVER:
  IMS_PER_BATCH: 1
  LOG_PERIOD: 1
  VISUALIZE_PERIOD: 1000
  VAL_PERIOD: 1
  CHECKPOINT_PERIOD: 500
  MAX_EPOCHS: 5000
  LR_DROP: 4000

OUTPUT_DIR: "/p300/projects/scene_graph/sggtr/outputs/sggtr"
