MODEL:
  DETECTOR:
    TYPE: "SGGTR"
    ENC_LAYERS: 3
    DEC_LAYERS: 3

  DETECTION_HEADER:
    BOX_FORMAT: "bx1by1bx2by2"

    NUM_OBJ_CLASS: 100 # 150
    NUM_REL_CLASS: 70 # 50

LOSS:
  SGG_ONLY: True

DATASETS:
  TRAIN: ("VRD_train", ) # ("VG_stanford_filtered_with_attribute_train", )
  VAL: ("VRD_val", ) # ("VG_stanford_filtered_with_attribute_val", )
  TEST: ("VRD_test", ) # ("VG_stanford_filtered_with_attribute_test", )

SOLVER:
  IMS_PER_BATCH: 8
  LOG_PERIOD: 10
  VISUALIZE_PERIOD: 200
  VAL_PERIOD: 100000000
  CHECKPOINT_PERIOD: 5
  MAX_EPOCHS: 500
  LR_DROP: 400

  LR_BACKBONE: 1e-4

OUTPUT_DIR: "/p300/projects/scene_graph/sggtr/outputs/full_vrd_sggtr_ssg_ob_bbwh_e3d3_sgg_only_without_fix_backbone"
